### ISSUE TITLE
Export fandom cargo tables as JSON

### ISSUE THREAD

**Issue by chlbowie** [Project-Path-of-Exile-Wiki/wiki#10]
https://pathofexile.fandom.com/wiki/Special:CargoTables
https://www.mediawiki.org/wiki/Extension:Cargo/Exporting_data

**Comment by pm5k** [comment]
Tables are now exported and sitting with @Journeytojah.

As mentioned on discord, I have made a tool to do this sort of thing so that we can utilise it in the future if need be. Once I finalise the docs/tests for it, it'll go into a repo and get backlinked here.
