### ISSUE TITLE
Export a list of all 70k pages URL

### ISSUE THREAD

**Issue by chlbowie** [Project-Path-of-Exile-Wiki/wiki#11]
Please help export a list with of URL of each page (and subject if possible)
I want to start review and tagging pages to estimate workload
Also to help organizing it before assigning task to editors.

**Comment by chlbowie** [comment]
DemonEach is working on it

**Comment by DemonEach** [comment]
iamacyborg did a great job he provided a google sheet with all of them: https://docs.google.com/spreadsheets/d/1hO_vjO7PUYjQxdacukN5tXbZR-Wm47QprjOPslNh4KU/edit?usp=sharing
