### ISSUE TITLE
Replica Maloney's Mechanism missing from the Trigger page

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#115]
https://www.poewiki.net/wiki/Trigger

https://www.poewiki.net/wiki/Replica_Maloney%27s_Mechanism

**Comment by angelic-knight** [comment]
Fixed. Replica Maloney's just needed a null edit.
It was missing the entry in item_stats for the trigger mod

**Comment by acbeaumo** [comment]
Closing, as this has already been fixed.
