### ISSUE TITLE
Maps are missing icons

### ISSUE THREAD

**Issue by zao** [Project-Path-of-Exile-Wiki/wiki#120]
All regular maps seem to be missing their icons, both when mentioned in text and also on their pages.

Examples: (https://www.poewiki.net/wiki/Underground_Sea_Map)
![image](https://user-images.githubusercontent.com/260218/143017249-c952c6c4-3a49-4ba1-8975-74e41d284537.png)
![image](https://user-images.githubusercontent.com/260218/143017271-610747ca-c84f-4cf7-b08c-ec28b9a20ffc.png)

**Comment by acbeaumo** [comment]
At some point, this was resolved.
