### ISSUE TITLE
The drop_enabled Base Item parameter's meaning is overloaded.

### ISSUE THREAD

**Issue by angelic-knight** [Project-Path-of-Exile-Wiki/wiki#121]
## Summary - The drop_enabled Base Item parameter's meaning is overloaded.
There are a few different cases where drop_enabled=false is used.
1. The item exists and functions, but no longer drops (e.g. eternal orbs)
2. The item exists and does not function (but used to have a function), and also no longer drops (e.g. Perandus Manor)
3. The item does not exist anymore, as all existing versions were converted (e.g. old watchstones in 3.16)

It would be beneficial to have distinct flags for these different meanings of drop_enabled.
Flagging items as not functional may not have significant enough value for a cargo field & template parameter.

## Perceived impact
2 - should only really matter for cargo queries at this point

**Comment by acbeaumo** [comment]
I agree that 1 and 3 should be distinguished. There should be a flag separate from drop_enabled that is used to denote items that don't exist in the game.

As for 2, I don't see any reason to distinguish this with a template flag. It should suffice to explain in the article text that the Perandus Manor no longer functions in the Map Device, for example.

**Comment by acbeaumo** [comment]
I'd like to get opinions on what the template parameter should be for flagging items that do not exist in the game.

Some suggestions:

- `is_playable = false`
- `is_in_game = false`
- `is_not_in_game = true`
- `is_void = true`
- `does_not_exist = true`
- `exists = false`

**Comment by angelic-knight** [comment]
I think it should be something like not_obtainable.
According to the trade site, people still have the watchstones from the old regions, which means that they haven't all been converted automatically.

However I think it will convert then before a trade could take place, so they're not obtainable, but they technically still exist.

That said, I don't think this distinction is very significant. For wiki readers, there's no real difference between exists-but-cannot-obtain and does-not-exist.

I do strongly prefer that the default be false, (so it must be set to true for unobtainable/non-existent items) which will impact the wording.

**Comment by acbeaumo** [comment]
That could work.

I'm guessing that the actual conversion takes place when the items are loaded in game – in a character inventory or a stash tab. This is why it is necessary for the old items to still exist in the game data.

**Comment by acbeaumo** [comment]
The item template now has the `is_in_game` parameter, which is used to differentiate between items that are drop disabled but exist in the game from items that no longer exist in the game but are still retained on the wiki for historical purposes.

**Comment by acbeaumo** [comment]
I think this can be closed now, since there hasn't been any follow up discussion.
