### ISSUE TITLE
Atlas_regions table data is out of sync with atlas_maps, which breaks joins

### ISSUE THREAD

**Issue by mark-phaedrus** [Project-Path-of-Exile-Wiki/wiki#122]
The atlas_regions table data still has the eight regions from pre-3.16 (with IDs like "InsideBottomLeft"), rather than the four regions from 3.16 (with IDs like "BottomLeft"). Since atlas_maps now uses the 3.16 IDs, This means that anything that tries to join atlas_maps with atlas_regions is busted. This is why the {{Query atlas maps}} table on all the region pages now has zero rows.

**Comment by angelic-knight** [comment]
Ran the PyPoE export for atlas stuff
`pypoe_exporter wiki lua atlas -wr`
atlas_regions and atlas_base_item_types tables are fixed now.

**Comment by mark-phaedrus** [comment]
Thank you!
