### ISSUE TITLE
There should be an easy way to query the most recent version of a map

### ISSUE THREAD

**Issue by mark-phaedrus** [Project-Path-of-Exile-Wiki/wiki#125]
In order to put together some Cargo tables for maps, I need a way to query only the most recent version of a given map. Oddly, there doesn't appear to be a good way to do that. Filtering on drop_enabled=0 does too much -- in some cases, the most recent version of the map isn't drop-enabled either. In theory, it looks like I could look for the map with a given name with the highest items.release_version value; but that seems hellish to do from a Cargo query. (And there doesn't seem to be a way to do it using {{Item table}} either.)

**Comment by angelic-knight** [comment]
Are you asking for maps in the most recent map series, or the most recently released version of each map (including Perandus Manor and maps that are out of the rotation)?

**Comment by mark-phaedrus** [comment]
Well, we'll need both, I'm sure. :) But I was specifically asking about the most recently released version of each map. If I have that, I can further filter with properties like is_drop_disabled and removal_version to check for things like The Perandus Manor.

**Comment by acbeaumo** [comment]
It should be possible to get the most recent version of a map by joining the query with the map_series table.

**Comment by acbeaumo** [comment]
I left this issue open for a while in case anyone wanted to discuss it further. I'm closing it now, since there is already a way to query the most recent version of a map by joining on the map_series table and ordering by map_series.ordinal DESC.
