### ISSUE TITLE
The "Manage TemplateData" button on template pages seems to be broken

### ISSUE THREAD

**Issue by mark-phaedrus** [Project-Path-of-Exile-Wiki/wiki#126]
The "Manage TemplateData" button on template and template/doc pages seems to have failed sometime in the last few weeks. Pressing it causes the page to scroll a bit but otherwise has no effect. This makes it tedious to document templates in the preferred TemplateData format.

**Comment by acbeaumo** [comment]
TemplateData is mostly intended to provide instructions to visual editors ("WYSIWYG"), which we're not using.
