### ISSUE TITLE
Lots of double redirects on legacy map pages

### ISSUE THREAD

**Issue by mark-phaedrus** [Project-Path-of-Exile-Wiki/wiki#128]
There are a _lot_ of legacy map pages that are currently broken due to double redirects. A typical example:

Arachnid Nest Map (pre 2.4) (edit) →‎ Arachnid Nest Map (The Awakening) →‎ Map:Arachnid Nest Map (The Awakening)

Fixing them manually would be a massive pain. Is it possible to automate a fix for this?

**Comment by acbeaumo** [comment]
It was a painstaking process, but I went through and cleaned these up some time ago.
