### ISSUE TITLE
Guide for How to ask for permission to edit wiki

### ISSUE THREAD

**Issue by chlbowie** [Project-Path-of-Exile-Wiki/wiki#13]

**Comment by mark-phaedrus** [comment]
Do you still need to ask for editing permission? I know I had to ask for a Discord role, but I think the editing permissions on the Wiki itself were there as soon as I signed up for an account.

**Comment by acbeaumo** [comment]
> Do you still need to ask for editing permission? I know I had to ask for a Discord role, but I think the editing permissions on the Wiki itself were there as soon as I signed up for an account.

The Editor role on Discord just allows you to see the #editing channel. No special permissions are required to edit the wiki. You just need an account.

**Comment by mark-phaedrus** [comment]
This can be closed then.

**Comment by chlbowie** [comment]
This was a legacy issue as the original design will require elevated access to edit wiki.
this can be closed now.
