### ISSUE TITLE
Fragmented Incubator indexing incorrectly

### ISSUE THREAD

**Issue by blvcksvn** [Project-Path-of-Exile-Wiki/wiki#132]
## Summary - [Fragmented Incubator indexing incorrectly]
[Fragmented Incubator page incorrectly indexing unobtainable rewards - https://www.poewiki.net/wiki/Fragmented_Incubator]

## Reproduction steps
[N/A]

## Expected outcome
[Only the following are confirmed to drop:

Shaper frags
Elder frags
Sacrifice frags
Mortal frags
Conqueror Crests
Offering to the Goddess

Unsure about Uber Elder fragments, have not seen any personally]

## Actual outcome
[Incorrectly showing the following:

Breachstones (all variants)
Timeless Emblems
Unrelenting Timeless Emblems
Divine Vessel
Blood-filled Vessel
Sacred Blossom
SImulacrum
The Maven's Writ
Upgraded Offering to the Goddess

Likely result of querying all items where |class_id = MapFragment ]

## Browser
[Google Chrome]

## Browser version
[Version 97.0.4692.99 (Official Build) (64-bit)]

## Perceived impact
[5]

## Screenshots
[
![image](https://user-images.githubusercontent.com/8675122/152427392-523356cd-7ef5-4940-a0de-70159d1e73d4.png)
]

**Comment by acbeaumo** [comment]
This has been taken care of for a long time now. I just forgot to close it.
