### ISSUE TITLE
Unable to upload semi-large Files under the filesize limit

### ISSUE THREAD

**Issue by mtxfellen** [Project-Path-of-Exile-Wiki/wiki#151]
**Describe the bug:**
```
413 Request Entity Too Large
nginx/1.18.0 (Ubuntu)
```
**Reproduction steps:**
Error is returned upon attempting to upload a file of 2.14MB (wiki specifies that the limit is 8MB).

**Comment by pm5k** [comment]
Can confirm, tried with a CC photo (4.1MB) from Pexels, and it failed to upload with the same error. This is under investigation.

**Comment by pm5k** [comment]
FYI these are the test results:
```
504x355   @ 84.3 KiB       -- Success
1008x711  @ 309.7 KiB      -- Success
2016x1423 @ 1.1 MiB        -- Failed
1920x1080 @ 726.7 KiB      -- Success
2560x1440 @ 1.3 MiB        -- Failed
2560x1440 @ 120 KiB        -- Success
```
Notice that the resolution actually does not matter, and it seems like the 8mb limit is not accurate and instead anything above 1mb (roughly) seems to be rejected.

**Comment by pm5k** [comment]
This has been fixed now.
