### ISSUE TITLE
Text Wrapping for Monster Unique Aura on Hallowed Ground Map Broken

### ISSUE THREAD

**Issue by BlackAura** [Project-Path-of-Exile-Wiki/wiki#179]
https://www.poewiki.net/wiki/Hallowed_Ground

Firefox 116.0.3, 64-bit
Windows 11

Running on a portrait monitor I get this experience:

![image](https://github.com/Project-Path-of-Exile-Wiki/wiki/assets/687604/c87e4eb4-36d6-4c0a-9dee-b9f3983cb562)

**Comment by lvlvllvlvllvlvl** [comment]
Changed the template from `{{ml|MonsterAuraSpeedUniqueMap1}}` to `{{ml|MonsterAuraSpeedUniqueMap1|display=stat_text}}`, which adds line breaks. Does that fix the issue for you?

Reference: https://www.poewiki.net/wiki/Template:ml
