### ISSUE TITLE
general guides (how to farm specific items, how to run the domain of timeless conflict, etc.)

### ISSUE THREAD

**Issue by Bdenner** [Project-Path-of-Exile-Wiki/wiki#19]

**Comment by acbeaumo** [comment]
You don't need to get permission to write guides. https://www.poewiki.net/wiki/Path_of_Exile_Wiki:Guides

**Comment by mark-phaedrus** [comment]
A consensus seems to be forming among the admins that guides should go on the forums and not the wiki. Should this be closed?

**Comment by pm5k** [comment]
After a discussion around this matter, it has become clear that the best course of action is to retain the existing guides, but bring them up to date gradually and try to keep them up to date incrementally every quarter (in line with major league releases). Deleting guides has been deemed detrimental to SEO and would constitute a loss of value.

As such, we should utilise this link to look at the guides:
https://www.poewiki.net/wiki/Special:AllPages?from=&to=&namespace=10014

and then bring them up to date slowly. We should also try to prefix (at the top of the guide) what version is this guide currently at and what date what’s this done on. For instance:

Accurate as of v3.16, 04-12-2021

**Comment by pm5k** [comment]
Closing ticket.
