### ISSUE TITLE
Initial dynamite carrying capacity is written 3 instead of 2 In the delve page > dynamite section > last line before accordion 

### ISSUE THREAD

**Issue by masudalimran** [Project-Path-of-Exile-Wiki/wiki#192]
<img width="1502" alt="Screenshot 2024-10-13 at 11 42 10 AM" src="https://github.com/user-attachments/assets/fb080083-e713-497e-ba7b-6c5a0d4a5df5">

**Comment by blvcksvn** [comment]
Simple editing issues like these should not be reported here, anyone can fix this by creating an account on the wiki.

**Comment by masudalimran** [comment]
My apologies. I didn’t know about it. I will try looking into it.

Masud Al Imran
Software Engineer
BISMIB TECHNOLOGY
Email: ***@***.***
Phone +880 1315686147
Website:  masud-al-imran.netlify.app
Github: https://github.com/masudalimran
