### ISSUE TITLE
Hello, you update I beat but strange, when you new career!

### ISSUE THREAD

**Issue by legendsrabbit** [Project-Path-of-Exile-Wiki/wiki#193]
It took me four days to chart T4 using the trigger ice method! Then nerf can't play, I can't fight monsters now, level 60 monsters can't fight! I don't know what to do. Do we start again? I spent all my currency building ice, and I don't even have gold to wash some... I don't hate you making adjustments but can you give me a free wash point, or let my ignition release free conversion under 4 days to make it 5 holes ，，，， or you new class ah, I can play again, I can't play now. Can only start again or wait for you to update...

**Comment by acbeaumo** [comment]
![confused](https://github.com/user-attachments/assets/ec2b5c4e-29c7-4bc7-8ab2-5a2c4a6d4681)
