### ISSUE TITLE
Modules broken in Relic page

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#26]
https://www.poewiki.net/wiki/Relic
 
![image](https://user-images.githubusercontent.com/11169733/130656684-68b1530a-41a8-4e24-b153-76bab73cb31f.png)

**Comment by jacquescorbytuech** [comment]
This is an easy one to fix if you have an account in the site.

You can go to the affected page and force a refresh by performing a null edit, ie press edit and then save without making any modifications. 

Happy to give you a quick walkthrough to show you how it’s done if that doesn't make sense.

**Comment by markliu06** [comment]
Most of them can be fixed by null edit.

I am still figuring out why Shadowstitch and String of Servitude articles are completely not working.

**Comment by markliu06** [comment]
This can be closed for now, as band-aid fixes are applied on  Shadowstitch and String of Servitude unique items
