### ISSUE TITLE
Missing thumbnails in Zana shop items

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#28]
https://www.poewiki.net/wiki/Zana,_Master_Cartographer#Crafting

**Comment by markliu06** [comment]
You mean crafting or https://www.poewiki.net/wiki/Zana,_Master_Cartographer#Decorations

For decoration. Just dig out the pic from game file (you can total cheat to check poedb the file path ) and extract it with zao 's command line software

https://www.poewiki.net/wiki/Path_of_Exile_Wiki:Community_portal#Uncompressed_DDS_files_from_the_ggpk_for_the_wiki
