### ISSUE TITLE
Parse game data for 3.15 using available tools.

### ISSUE THREAD

**Issue by pm5k** [Project-Path-of-Exile-Wiki/wiki#3]
Currently there's a need to have a quick and dirty dump of current 3.15 data which can be used to update the wiki itself to be more accurate.

The most pressing thing is that this is done quickly - so using currently developed tools such as:

- [RePoE](https://github.com/brather1ng/RePoE)
- [PyPoE](https://github.com/OmegaK2/PyPoE)
- [PoB Community](https://github.com/PathOfBuildingCommunity/PathOfBuilding)

Zao suggested checking this too - https://github.com/poe-tool-dev/ggpk.discussion/wiki/Implementations

For the first iteration - just getting the accurate data is fine. Later this can become an effort to roll custom tooling which works with the automation flow for this repo.

**Comment by Spawnbroker** [comment]
It looks like RePoE has most of the stuff we'd need from 3.15.1 in their fork in the data folder: https://github.com/brather1ng/RePoE/tree/master/RePoE/data

Would it be worth the effort to set up a docker container that does all of the setup needed to load all of this? Might be worthwhile and would make the dev experience easier.

**Comment by markliu06** [comment]
Ok, i have setup the to do list inside wiki.

https://www.poewiki.net/wiki/Path_of_Exile_Wiki:To-do_list/3.15.0

Last time i use pypoe, the monster datacard are able to export

the fork has a lot of rowsize error .

For Blight's rowsize error, it was fixed but i guess better doc the change here in this repository or at brather1ng's repository 

https://github.com/Project-Path-of-Exile-Wiki/wiki/issues/42

The crafting bench was able to export in August but today it has 

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "CraftingBenchOptions.dat": Specification row size 175 vs real size 191`

The monster lua's error is

`KeyError: 'TagsKeys'`

pantheon lua's error is

`TypeError: Uncaptured quantifier canonical_line, add in PyPoE/poe/translations.py`

for atlas lua the error is

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "AtlasRegions.dat": Specification row size 20 vs real size 68`

for bestiary lua the error is (despite it is unchanged between 3.14 and 3.15)

`PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "BestiaryRecipes.dat": Specification row size 38 vs real size 42`


OT parameter works fine
![Uploading Screenshot 2021-09-11 151608.png…]()

**Comment by markliu06** [comment]
Done minimap lua export
