### ISSUE TITLE
Numbered lists are hard to read

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#30]
## Bug - List numbers are hard to read
It looks like list numbers, styled by the class "tocnumber" is set to "color: #202122" which is quite hard to read on a background of #141414 (styled by div#toc, div.toc,)

## Reproduction steps
Navigate to https://www.poewiki.net/wiki/List_of_unique_body_armours

## Expected outcome
Numbers by page sections are more visible (lighter color?)

## Actual outcome
Numbers by page sections are very hard to read.

## Environment
- Google Chrome
- Version 92.0.4515.159 (Official Build) (64-bit)
- Linux

## Perceived impact
2

![image](https://user-images.githubusercontent.com/11169733/130657111-59daa952-6b7e-49ef-9905-0162369ba50c.png)

**Comment by angelic-knight** [comment]
I've submitted a fix to the CSS that fixes this in discord.
See message https://discord.com/channels/872882365406523452/873265604671438948/889001079797321730

Just needed a line with 
`.tocnumber{
    color: inherit;
}`

**Comment by acbeaumo** [comment]
I have applied a fix.
