### ISSUE TITLE
Module errors in meta crafting mods

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#33]
## Reproduction steps
https://www.poewiki.net/wiki/Guide:Crafting#Meta-crafting_modifiers

## Expected outcome
[What was supposed to happen normally?]

## Actual outcome
screenshot

## Environment
- Browser
- Browser version
- Any extensions that touch CSS/HTML on all websites (adblock, ublock, etc..)
- Any other relevant info about your local environment

## Perceived impact
[How bad do you consider this to be on a scale from 1-10, be realistic - not hyperbolic]

## Screenshots
[Attach screenshots at the end]

![image](https://user-images.githubusercontent.com/11169733/130662613-8c307080-21e6-4df4-a0ed-fd1286de6870.png)

**Comment by jacquescorbytuech** [comment]
Errors cleared.

![image](https://user-images.githubusercontent.com/49435000/130663372-26382231-bc85-4876-bb72-791335bab1c2.png)
