### ISSUE TITLE
Duplicated beasts in beastcrafting

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#34]
## Bug - Duplicated beasts
Beast components on Beastcrafting page are duplicated (sometimes even 4 times)

## Reproduction steps
Go to https://www.poewiki.net/wiki/Beastcrafting

## Expected outcome
Only one beast entry per craft

## Actual outcome
More than one beast entry

## Environment
- Browser Firefox
- Browser version 91.0
- Any extensions that touch CSS/HTML on all websites (adblock, ublock, etc..)
- Any other relevant info about your local environment

## Perceived impact
2 (it's just confusing and ugly)

## Screenshots
[Attach screenshots at the end]
![image](https://user-images.githubusercontent.com/11169733/130989413-0d4fc054-5ca1-4080-837d-a38836ec8d47.png)

**Comment by markliu06** [comment]
I null edit every single cargo table and then the front end seems fixed it

https://www.poewiki.net/wiki/Template:Bestiary
