### ISSUE TITLE
List of rewards missing from The Gentleman

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#35]
## Bug - [brief one sentence summary goes here]
Missing list of rewards on "The gentleman" divination card page

## Reproduction steps
Go to https://www.poewiki.net/wiki/The_Gentleman

## Expected outcome
List has ever possible sword that can be obtained from the card

## Actual outcome
List displays an error text: "Lua error in Module:Item_acquisition at line 650: table index is nil."

## Environment
- Browser: Chrome
- Browser version: 92.0.4515.159

## Perceived impact
3? Not a big problem since the list is on the official wiki, but would be nice for the future

## Screenshots
![image](https://user-images.githubusercontent.com/11169733/130989539-de3d4431-133d-429d-8af6-e14d15caf679.png)

**Comment by acbeaumo** [comment]
This may have been fixed already. Consider closing the issue.
