### ISSUE TITLE
List of anointment is completely wrong

### ISSUE THREAD

**Issue by AlphSpirit** [Project-Path-of-Exile-Wiki/wiki#42]
https://www.poewiki.net/wiki/Oil#List_of_anointments

The list is missing a lot of anointment and has wrong data as well.

![image](https://user-images.githubusercontent.com/11169733/131019592-1bc0f497-1e1c-43f0-a858-22d785ffe207.png)

**Comment by angelic-knight** [comment]
I've figured out how to tweak specifications for PyPoE (you can adjust fields in the `...\PyPoE\poe\file\specification\data\stable.py` file) and I've gotten it to output .lua files which seem to have recipes and outcomes for anointments.

I'm not sure where to go from here - I'm not sure how I would update the Cargo Database, and if there's any way to preview the affects of updating the DB (or if we can back up the old state before updating it?).

**Comment by markliu06** [comment]
If you have the lua , post those in the sub page of https://www.poewiki.net/wiki/Module:Blight

and then null edit those template of https://www.poewiki.net/wiki/Template:Blight (all sub templates) 

and then null edit the front side article such as https://www.poewiki.net/wiki/List_of_anointments

https://www.poewiki.net/wiki/Blight_(game_mechanic)

The modifier may still be wrong but the oil combo should be correct

**Comment by angelic-knight** [comment]
Thanks for the help!
I also found [the PyPoE page](https://www.poewiki.net/wiki/Path_of_Exile_Wiki:PyPoE) after posting the comment, which has a lot of info about how Cargo stores data on the wiki, and how to use PyPoE to update the wiki.

I've updated the recipe and recipe_item sub-modules, and performed null edits to trigger updates.

**Comment by Journeytojah** [comment]
This has been fixed thanks to @angelic-knight and @markliu06.
