### ISSUE TITLE
small passive table in ascendency class article

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/wiki#44]
## Bug

Seems cargo table or the template: Query ascendancy passive skills has something wrong, which show the wrong passive from other ascendancy class

## Reproduction steps

e.g. 
https://www.poewiki.net/wiki/Pathfinder#Minor_skills

## Expected outcome

should not show the ascendency passive skill point Patherfinder of the Ascendant

  adding query code can bypass the problem 
  
  https://www.poewiki.net/wiki/Special:Diff/1079775 (Raider)
  
  ## Environment

Microsoft Edge

## Perceived impact

5
  
  
  ## Screenshots

![Screenshot 2021-08-27 192448](https://user-images.githubusercontent.com/67254854/131120509-e2159fa1-c63b-4048-bfbf-2f1d442ec558.png)

**Comment by Journeytojah** [comment]
Fixed for all ascendancies.
