### ISSUE TITLE
Unused columns in skill gem level tables

### ISSUE THREAD

**Issue by worldendDominator** [Project-Path-of-Exile-Wiki/wiki#46]
Pages for skill gems have tables that list their stats at every level. Those tables always have a columns for generic gem stats (like damage effectiveness, duration and cooldown) that are not always present on the gem, and are not separated for active and support gems, so there's a lot of useless columns filled with zeroes.

When a stat exists on a gem, but doesn't change with level, it will also be zeroes.

**Comment by markliu06** [comment]
Do you have some example? Since gem rework may break the table and some column can be deleted via wiki code on that gem article

**Comment by worldendDominator** [comment]
Anything I tried to open, basically. But for example, [Cruelty](https://www.poewiki.net/wiki/Cruelty_Support):
![изображение](https://user-images.githubusercontent.com/6707627/131202989-af0a201b-066b-465d-bbcf-7f87b4345364.png)

Also, unrelated to this issue, values in the table are not updated for 3.15.0d.

**Comment by markliu06** [comment]
> Also, unrelated to this issue, values in the table are not updated for 3.15.0d.


This is due to pypoe is down and it is tedious to edit all support gem manually one by one (or we can have division of labour by everyone adopt an article)

**Comment by markliu06** [comment]
For the empty column. It does hidden in fandom POE wiki. So that i guess the problem may be due to cargo table stored the value wrongly.

**Comment by Xebtria** [comment]
is there any chance of pypoe coming back or any other automated solution emerging that fixes the values not being up2date in the table? besides the table listing 50 stats which are not present on the gem and thus being such a huge table, the not updated values is the biggest issue I personally have with the wiki right now.

**Comment by jacquescorbytuech** [comment]
It's not a case of pypoe "coming back", we need to get it working for the new versions of the game. If you've got any experience with python any help you could provide on that front would be greatly appreciated :)

**Comment by markliu06** [comment]
I would always say it is two parts. Familiar or willing to know how to extract raw file from ggpk, view it and check the pypoe is able to extract the data or not. Or required to add more line and fix bug of pypoe, which is written in python

**Comment by Xebtria** [comment]
> It's not a case of pypoe "coming back", we need to get it working for the new versions of the game. If you've got any experience with python any help you could provide on that front would be greatly appreciated :)

sadly not, the best programming skills I could offer is a bit of wonky batch file coding, but I wouldn't even call that "programming skills" to begin with tbh. I am just a lonely end user being sad about the gem level tables on the wiki being in the sad state they are and I found this issue which was still open so I wanted to check on the status :(

**Comment by markliu06** [comment]
BTW. May be band-aid fix is adding parameter to hide column instead of auto show all column with non-empty data.

But it may need a lot of manual edit to determinate which column need to hide and edit article one by one

**Comment by acbeaumo** [comment]
This issue appears to be fixed now with the tweaks to Cargo.
