### ISSUE TITLE
Some pages are not indexed by search engines

### ISSUE THREAD

**Issue by nielsvanee** [Project-Path-of-Exile-Wiki/wiki#49]
## Bug
Some pages are not indexed in search engines.

## Reproduction steps
Search either on Google.com or Duckduckgo.com (two tested) for "poewiki.net Expedition's End" and the relevant page will not show up

## Expected outcome
The page shows up in *at least* very specific searches

## Environment
Google.com / Duckduckgo.com

## Perceived impact
2 / 10

## Screenshots
![image](https://user-images.githubusercontent.com/16431767/131264903-b1916cda-c2d5-46e6-91df-7b5f3b8bbb31.png)

**Comment by nielsvanee** [comment]
Possible reasons:
Robots.txt missing
nofollow is somehow active

**Comment by Journeytojah** [comment]
![image](https://user-images.githubusercontent.com/10452321/131360462-25cc6cf3-20f8-4ae9-914b-15b4116df832.png)

This should help. Keeping this open for now.

**Comment by Tntmister** [comment]
I've found some more searches that result in the intended page not appearing in the search results, Barrage and Southbound
![firefox_vxUYDmZ1rQ](https://user-images.githubusercontent.com/38975134/133845104-bf6107de-b81e-4a56-9d8b-4e9667c7aa70.png)
![firefox_mDpzi8UrH6](https://user-images.githubusercontent.com/38975134/133845106-8a05a5f4-0850-4376-b9c8-cb126c2c4d87.png)
