### ISSUE TITLE
Suggestion: Map should have one article and the legacy map info should be in new namespace so that hidden in search

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/wiki#71]
## Bug / Issue

The issue is, currently, map have a main article, and then a lot of child articles to store the info of legacy info, mainly the infobox of the legacy map. But a map would have Expedition , Ritual. Heist, up to the "Original", etc, for a total of 14 map series , so that it confuse people where to read

## Expected Outcome

The wiki bot, or any people that try to search the map should return one article , while the infobox info should store in new namespace and hidden from default search

## Other info

Old discussion thread

https://www.poewiki.net/wiki/Path_of_Exile_Wiki_talk:Community_portal#About_pages_for_map_items

## Screenshot

![2021-09-10](https://user-images.githubusercontent.com/67254854/132788780-55bdefe0-ee24-4bbd-841b-50843f8608c6.png)

**Comment by jacquescorbytuech** [comment]
New Map namespace created

```
define("NS_MAP", 10016); 
define("NS_MAP_TALK", 10017);
$wgExtraNamespaces[NS_MAP] = "Map";
$wgExtraNamespaces[NS_MAP_TALK] = "Map_talk";

**Comment by jacquescorbytuech** [comment]
New Namespaces showing up in the Wiki search

![image](https://user-images.githubusercontent.com/49435000/133291888-b89610cf-b2d1-4f90-a2f4-73af0c2f2063.png)

**Comment by acbeaumo** [comment]
Great. I suppose the first thing I can do is move everything over and leave redirects. That shouldn't break anything, right?

**Comment by jacquescorbytuech** [comment]
I think that should be okay.

**Comment by markliu06** [comment]
Move everything should be fine. Just the unique map transclude and the content transclude need to double check .


Or just move the base maps of vinkar square to see how it will behave? Since the legacy table use a lot of item link to the legacy map item

**Comment by acbeaumo** [comment]
I'm thinking eventually all of the map data will live in the Map namespace, but we will still use the map articles in the main namespace – the ones that don't have parentheses like [Fields Map](https://www.poewiki.net/wiki/Fields_Map) and [Cemetery Map](https://www.poewiki.net/wiki/Cemetery_Map).

My reasoning for doing it this way is that it should be easier to maintain. When GGG creates a new map series, we can import the new maps directly into the Map namespace. The main namespace article won't necessarily have to be updated.

**Comment by markliu06** [comment]
fixed some il error in 

https://www.poewiki.net/wiki/Version_0.10.0#Content

so the final road block would be il that link to legacy map item child article instead of main page

**Comment by acbeaumo** [comment]
Item link template has been updated to check for redirects when `page=` is used. This should mean fewer errors appear as a result of moving the map pages.

**Comment by markliu06** [comment]
And should i just use AWB to add the "Map:" prefix in between

`{{Map item drops
|page = Beach Map ({{Current map series}})
}}
{{Item acquisition
|page = Beach Map ({{Current map series}})
}}
{{Item unique versions
|base_item = Beach Map ({{Current map series}})
}}`

Or change the template as well?

**Comment by acbeaumo** [comment]
I'll see if I can update the templates.

**Comment by acbeaumo** [comment]
Template:Map item drops and Template:Item acquisition have both been updated to check for redirects when `|page=` is used.

I'm not sure whether Template:Item unique versions needs to be updated.

**Comment by markliu06** [comment]
may be i would just nuke it out from legacy map article and then edit the current map series with AWB in next week

**Comment by markliu06** [comment]
Ok, https://www.poewiki.net/wiki/Hallowed_Ground as main article recreated, 

Hallowed Ground (Betrayal) , Hallowed Ground (Legion)  just boldly change to redirect as i there is no need to have fork article and the infobox does not store much info, unlike the legacy basetype

**Comment by AlphSpirit** [comment]
There are now only 2 links for each map, on for the current map and one for the disambiguation article.
