### ISSUE TITLE
duplicate rows in crafting bench

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/wiki#72]
## Bug

Seems cargo table bug. Every single crafting bench options are doubled .

## Reproduction steps

https://www.poewiki.net/wiki/Crafting_Bench#Crafting_modifiers
https://www.poewiki.net/wiki/Beast_Burrow

Either before i update the backend module or after, they are duplicated . Null edit does not fix it

Raw data does not duplicate

https://www.poewiki.net/wiki/Module:Crafting_bench/crafting_bench_options_costs
https://www.poewiki.net/wiki/Module:Crafting_bench/crafting_bench_options

## Expected outcome

Each option should have only one entry

## Actual outcome

Each options have two entries

In https://www.poewiki.net/wiki/Template:Crafting_bench/cargo/crafting_bench_options

it wrote This template defines the table "crafting_bench_options". View table. **A replacement table has been generated for this table; View replacement table.**

## Environment

Microsoft Edge

## Perceived impact

3

## Screenshots

![Screenshot 2021-09-10 223022](https://user-images.githubusercontent.com/67254854/132869952-fe5afbe2-8f24-486c-bac1-aae2ae4f1836.png)

**Comment by markliu06** [comment]
Ok, i saw Iamacyborg has done something in wiki

https://www.poewiki.net/wiki/Special:Diff/1088817

So that i guess i have to have a look at pypoe to see the lua export script need to change in order to prevent this to happen again

(or requires changing "crafting_item_class_categories" to "item_class_categories" again manually )

**Comment by acbeaumo** [comment]
Yeah, we had to shorten the name of that field for weird technical reasons.

**Comment by markliu06** [comment]
Ok , note to self

somewhere in the middle 1421~ish row

https://github.com/OmegaK2/PyPoE/blob/dev/PyPoE/cli/exporter/wiki/parsers/lua.py

or 

https://github.com/brather1ng/PyPoE/blob/dev/PyPoE/cli/exporter/wiki/parsers/lua.py

need to change "crafting_item_class_categories" to "item_class_categories"

(On top of rowsize error)
