### ISSUE TITLE
All image info is lost

### ISSUE THREAD

**Issue by ufuksarp** [Project-Path-of-Exile-Wiki/wiki#74]
Information such as upload date, uploader, file history is lost. Every image just says it's uploaded at 7 August 2021.

**Comment by jacquescorbytuech** [comment]
Unfortunately due to the way images are added to the wiki, I don't think there's a way around this.

**Comment by markliu06** [comment]
I think it may need people to copy the info one by one from the old fandom wiki

**Comment by jacquescorbytuech** [comment]
I don't believe that that is possible.

**Comment by jacquescorbytuech** [comment]
One thing to note is you can still see a history of the File page itself, for example https://www.poewiki.net/wiki/history/File:Class_select.jpg

**Comment by markliu06** [comment]
> One thing to note is you can still see a history of the File page itself, for example https://www.poewiki.net/wiki/history/File:Class_select.jpg

yeah i think it is sufficient
