### ISSUE TITLE
no Gem list page

### ISSUE THREAD

**Issue by IzVR-X** [Project-Path-of-Exile-Wiki/wiki#75]
When u search for gems, does not give you page with gem list like before: pathofexile.fandom.com/wiki/List_of_active_skill_gems

**Comment by acbeaumo** [comment]
This issue needs more info. Please refer to the guidelines for [reporting issues](https://github.com/Project-Path-of-Exile-Wiki/wiki/wiki/Reporting-issues).

**Comment by markliu06** [comment]
Still there
![2021-09-24](https://user-images.githubusercontent.com/67254854/134655836-99a009ea-deca-465c-a8bc-917e2431d7ae.png)

**Comment by AlphSpirit** [comment]
When you search for Gems, you get to the Active skill page, which has a link to the list of active skill gems right at the top.
