### ISSUE TITLE
Crafting Bench page has broken database references

### ISSUE THREAD

**Issue by anttikpmg** [Project-Path-of-Exile-Wiki/wiki#76]
## Summary 
The Crafting Bench page has references to field name "crafting_item_class_categories" which causes an error

## Reproduction steps
visit https://www.poewiki.net/wiki/Crafting_Bench

## Expected outcome
A list of crafting bench recipies & locations is shown
 
## Actual outcome
"Error: No field named "crafting_item_class_categories" found for any of the specified database tables" is shown in the recipe list section.

## Browser
All

## Browser version
Any

## Perceived impact
7

## Screens

![image](https://user-images.githubusercontent.com/26135965/133887470-4998fa19-0c51-4e9f-9fe7-d7af3f0fcd4e.png)

**Comment by markliu06** [comment]
probably due to this fix

https://github.com/Project-Path-of-Exile-Wiki/wiki/issues/72
