### ISSUE TITLE
Module:Item table need ward column

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/wiki#77]
## Bug 

Module:Item table current able to have =1 to toggle the ES, evasion or armour rating columns

But no column for ward yet

## Expected Outcome

Should have `ward =1` option or other abbreviation 

## Other info

https://www.poewiki.net/wiki/Template:Item_table

https://www.poewiki.net/wiki/Module:Item_table

**Comment by markliu06** [comment]
Also

The list cannot be displayed without the placeholder ES column

https://www.poewiki.net/wiki/List_of_unique_armours_granting_ward

**Comment by acbeaumo** [comment]
This has already been implemented. My bad for not updating the template documentation.

https://www.poewiki.net/w/index.php?title=List_of_unique_armours_granting_ward&type=revision&diff=1092953&oldid=1092915
