### ISSUE TITLE
Crafting Bench has missing unlock location

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/wiki#78]
## Summary

The table in Crafting Bench article no longer showing the unlock location of specific recipe

## Reproduction steps

visit 
https://www.poewiki.net/wiki/Crafting_Bench#Helena%20-%20Unlocked%20via%20objects

(probably due to pypoe again. As from this edit https://www.poewiki.net/w/index.php?title=Module:Crafting_bench/crafting_bench_options&diff=prev&oldid=1046047 , pypoe fails to export the module lua properly)

## Expected outcome

Listing the location

## Actual outcome

Location missing

## Browser

Any

## Perceived impact

7

## Screenshots
![Screenshot 2021-09-28 064421](https://user-images.githubusercontent.com/67254854/134995295-0d1c42ee-5870-4532-a720-ca9e622f1dfc.png)

![screenshot-0131](https://user-images.githubusercontent.com/67254854/134995448-4ec9faf2-4740-4d9d-b39b-1bfc4c355152.png)

**Comment by markliu06** [comment]
May be this issue should move to

https://github.com/Project-Path-of-Exile-Wiki/PyPoE/issues

**Comment by mark-phaedrus** [comment]
It looks like this has been previously fixed. I did make some changes to the table layout for better usability and readability.

**Comment by markliu06** [comment]
> It looks like this has been previously fixed. I did make some changes to the table layout for better usability and readability.

I think it is fixed by us but unsure which commitment
